[default]

SQLALCHEMY_DATABASE_URI = "postgresql://postgres:root@localhost/centro"

TITELE= "centro de formação visãofuturo"

SECRET_KEY = "SECRET_KEY"




EXTENSIONS = [
 "src.blueprint.restapi:init_app",
 "src.extension.command:init_app",
 "src.extension.database:init_app",
 "src.blueprint.web:init_app",
 

]



